---
title: "영상 탐색"
author: Sang-Il Lee
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
lightbox: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

## 개요

서울에 대한 Landsat 8 영상을 불러온다. 우선 필수적인 패키지를 설치한다.

```{r}
library(tidyverse)
library(terra)
library(tidyterra)
library(sf)
library(tmap)
```

Level-2 와 Level-1 데이터를 각각 불러온다.

```{r}
level2_landsat_seoul_st <- rast("D:/My R/World Data Manupulation/USGS EarthExplorer/level2_landsat_seoul_stack.tif")
level1_landsat_seoul_st <- rast("D:/My R/World Data Manupulation/USGS EarthExplorer/level1_landsat_seoul_stack.tif")
```

Level-2 단순 플롯 그리기.

```{r}
plot(level2_landsat_seoul_st, col = grey(0:100/100)) # 어두움
plot(stretch(level2_landsat_seoul_st, minq = 0.1, maxq = 0.99), col = grey(0:100/100)) # 밝음
```

Level-1 단순 플롯 그리기.

```{r}
plot(level1_landsat_seoul_st, col = grey(0:100/100)) # 어두움
plot(stretch(level1_landsat_seoul_st, minq = 0.1, maxq = 0.99), col = grey(0:100/100)) # 밝음
```

## 개별 픽셀값 확인

## 영상 통계 및 그래프

### 단변량

### 다변량

## 영상 프로파일링
