---
title: "영상 강조"
author: Sang-Il Lee
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
lightbox: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
editor_options: 
  chunk_output_type: console
---

## 개요

필수적인 패키지를 설치한다.

```{r}
library(tidyverse)
library(terra)
library(tidyterra)
library(sf)
library(tmap)
options(scipen = 999)
```

서울의 행정구역 바운더리 파일을 불러온다.

```{r}
#| results: hide 
seoul <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_SIDO_2023_2Q.shp")
seoul_gu <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_GU_2023_2Q.shp")
seoul_dong <- st_read("D:/My R/Korean Administrative Areas/행정구역 셰이프 파일/2 Original Cleaning/2023_2Q/SEOUL_EMD_2023_2Q.shp")
```

Level-2 데이터를 불러와 마스킹한다.

```{r}
level2_landsat_seoul_st <- rast("D:/My R/World Data Manupulation/USGS EarthExplorer/level2_landsat_seoul_stack.tif")
level2_landsat_seoul_st_mask <- level2_landsat_seoul_st |> 
  mask(seoul)
```

## 영상 축소 및 확대

## 대비 확장(contrast stretching)

### 최소-최대 대비 확장

대비 확장을 실행한다.

```{r}
level2_landsat_seoul_st_mask_st1_minmax <- level2_landsat_seoul_st_mask |> 
  stretch(minv = 0, maxv = 255)
```

히스토그램을 생성한다.

```{r}
#| fig-width: 19.4
#| fig-asp: 0.618
#| fig-dpi: 600
df_2 <- as.data.frame(level2_landsat_seoul_st_mask_st1_minmax, xy = FALSE, na.rm = TRUE)
df_long <- df_2 |> 
  pivot_longer(
    cols = everything(), names_to = "band", values_to = "DN"
  ) |> 
  mutate(
    band = fct(band, levels = str_c("B", 1:11))
  )
ggplot(df_long, aes(x = DN)) +
  geom_histogram(bins = 100) +
  facet_wrap(~ band, scales = "free_y") +
  theme(
    plot.title = element_text(size = 30), 
    axis.title = element_text(size = 20),
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16),
    legend.title = element_text(size = 17), 
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 20)
  ) +
  labs(
    x = "DN", 
    y = "Frequencies", 
    caption ="SANG-IL LEE, Geography Education at SNU, 2025") 
```

지도를 생성한다.

```{r}
#| fig-width: 15
#| fig-height: 10
#| fig-dpi: 600
tm_shape(level2_landsat_seoul_st_mask_st1_minmax, raster.downsample = FALSE) +
  tm_raster(style = "cont", palette = "-Greys", title = "DN") +
  tm_facets(ncol = 4, free.scales = FALSE) +
  tm_layout(legend.show = FALSE, panel.label.size = 2, 
            attr.outside = T, attr.outside.position = "bottom") +
  tm_credits(text = "SANG-IL LEE, Geography Education at SNU, 2025", size = 1.5, position = c(0.75, "top"))
```

### 표준편차(비중) 대비 확장

대비 확장을 실행한다.

```{r}
level2_landsat_seoul_st_mask_st1_prop <- level2_landsat_seoul_st_mask |> 
  stretch(minv = 0, maxv = 255, minq = 0.01, maxq = 0.99)
```

히스토그램을 생성한다.

```{r}
#| fig-width: 19.4
#| fig-asp: 0.618
#| fig-dpi: 600
df_2 <- as.data.frame(level2_landsat_seoul_st_mask_st1_prop, xy = FALSE, na.rm = TRUE)
df_long <- df_2 |> 
  pivot_longer(
    cols = everything(), names_to = "band", values_to = "DN"
  ) |> 
  mutate(
    band = fct(band, levels = str_c("B", 1:11))
  )
ggplot(df_long, aes(x = DN)) +
  geom_histogram(bins = 100) +
  facet_wrap(~ band, scales = "free_y") +
  theme(
    plot.title = element_text(size = 30), 
    axis.title = element_text(size = 20),
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16),
    legend.title = element_text(size = 17), 
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 20)
  ) +
  labs(
    x = "DN", 
    y = "Frequencies", 
    caption ="SANG-IL LEE, Geography Education at SNU, 2025") 
```

지도를 생성한다.

```{r}
#| fig-width: 15
#| fig-height: 10
#| fig-dpi: 600
tm_shape(level2_landsat_seoul_st_mask_st1_prop, raster.downsample = FALSE) +
  tm_raster(style = "cont", palette = "-Greys", title = "DN") +
  tm_facets(ncol = 4, free.scales = FALSE) +
  tm_layout(legend.show = FALSE, panel.label.size = 2, 
            attr.outside = T, attr.outside.position = "bottom") +
  tm_credits(text = "SANG-IL LEE, Geography Education at SNU, 2025", size = 1.5, position = c(0.75, "top"))
```

### 구간 대비 확장

### 히스토그램 균등화(histogram equalization)

대비 확장을 실행한다.

```{r}
level2_landsat_seoul_st_mask_st1_hist <- level2_landsat_seoul_st_mask |> 
  stretch(minv = 0, maxv = 255, histeq = TRUE)
```

히스토그램을 생성한다.

```{r}
#| fig-width: 19.4
#| fig-asp: 0.618
#| fig-dpi: 600
df_2 <- as.data.frame(level2_landsat_seoul_st_mask_st1_hist, xy = FALSE, na.rm = TRUE)
df_long <- df_2 |> 
  pivot_longer(
    cols = everything(), names_to = "band", values_to = "DN"
  ) |> 
  mutate(
    band = fct(band, levels = str_c("B", 1:11))
  )
ggplot(df_long, aes(x = DN)) +
  geom_histogram(bins = 100) +
  facet_wrap(~ band, scales = "free_y") +
  theme(
    plot.title = element_text(size = 30), 
    axis.title = element_text(size = 20),
    axis.text.x = element_text(size = 16), 
    axis.text.y = element_text(size = 16),
    legend.title = element_text(size = 17), 
    legend.text = element_text(size = 16),
    strip.text = element_text(size = 20)
  ) +
  labs(
    x = "DN", 
    y = "Frequencies", 
    caption ="SANG-IL LEE, Geography Education at SNU, 2025") 
```

지도를 생성한다.

```{r}
#| fig-width: 15
#| fig-height: 10
#| fig-dpi: 600
tm_shape(level2_landsat_seoul_st_mask_st1_hist, raster.downsample = FALSE) +
  tm_raster(style = "cont", palette = "-Greys", title = "DN") +
  tm_facets(ncol = 4, free.scales = FALSE) +
  tm_layout(legend.show = FALSE, panel.label.size = 2, 
            attr.outside = T, attr.outside.position = "bottom") +
  tm_credits(text = "SANG-IL LEE, Geography Education at SNU, 2025", size = 1.5, position = c(0.75, "top"))
```

## 공간 필터링(spatial filtering)
